### ISSUE TITLE
Create starting bad code for refactoring

### ISSUE THREAD

**Issue by zhon** [allan-stewart/react-hogwarts-tdd-kata#1]
I am thinking "the sorting hat" could be badly written by Malfoy.

Refactor from there.

**Comment by allan-stewart** [comment]
Per our discussion yesterday (Tuesday May 19), I'm going to work on this as part of "user story 2"

**Comment by zhon** [comment]
Story 1 flows nicely into Story 2 and uses the same interface. I am interested how you handle that.

My code was displaying the catalog (I just messed it up oops no tests). It will be moved as soon as we have a build. It "currently" runs with `npm start`

**Comment by allan-stewart** [comment]
I see your changes and things are running and rendering for me now. Going back over the angular version as a reference, I see what you mean about story 1 flowing into story 2. I think how I want to handle that is by having "Malfoy" write the existing code around one or more of: registration, wizard repository, and the schedule page.

So basically, I think it would be something where Story 2 starts off similar to how you had it in the old version, but once they hook it up, they notice it isn't working the way they expect. That leads them into Malfoy's untested/badly-tested code which they will have to refactor.

That's my current idea. I'm starting to hack on it in bits and pieces with the old version for reference up on the side. I hope to have something to commit tonight -- I think I'll start with a "pretty" version of it working, then work backwards to evil Malfoy code.

**Comment by zhon** [comment]
I am busy adding routing and moving all the code into a better directory structure. I am also editing the `README.md` as I go along.

You could have Malfoy use a different tab to put the code under. Then the refactor would include removing the tab and duplication.

**Comment by allan-stewart** [comment]
Good idea. Tonight I put some story 2 code in place and played with importing components. I need to read up more on both Alt and routing; I didn't try to mess with any of that yet (baby steps here). I'm starting to see how they can all fit together. Gonna need to try messing with tests soon too...

**Comment by zhon** [comment]
Thanks to @jaketrent I am starting to see how multiple file fit together. It is what I needed to start on the testing.

**Comment by allan-stewart** [comment]
I had another idea for Malfoy's bad code. In addition to just being badly written, what if he's also sneaking in a bug on purpose? Perhaps increasing the number of credits when a Slytherin house member registers for a course (so they don't have to take as many classes). Or inversely, reducing the number of credits for other houses so they think they need to take more classes.

The drawback to doing this would be that it adds some additional complication and therefore might make it take longer to unravel Malfoy's code.

**Comment by zhon** [comment]
It sounds fun. OTHO, I am in the desert all next week so I am a little panicked.

**Comment by allan-stewart** [comment]
Gotcha. Well, I'm still trying to grok how everything should fit together. I know you've been working on the tests, but I haven't tried helping out much there yet because I'm not sure how to separate the responsibility for some of the pieces (and therefore don't know what should be tested where). Specifically, I'm trying to figure out what should go in actions, stores, and repositories.

From some of the reading I've done, it sounds like stores are generally pretty "dumb". The actions should be the ones that manage the interactions -- in our case, call the repositories. I get that the repositories are for server communication (or simulated), but one of my big questions is when they should be invoked. For instance, if the schedule page needs catalog data, should it listen to that store? Should the wizard store know about catalog store? Or maybe the action should know about catalog store/repository?

So I'm working toward having a "finished" implementation of the pages. Once you and I are both happy with how all the pieces fit together, then I'll be a lot more confident in driving forward with testing. I still feel very new to most of the tech in our project here.

The long weekend was busy for me with family stuff, but I should have more time to devote to this over the next few days. Hopefully we can get to a better state before you are gone. And maybe I can do a hack session with Jake or something. :smiley:

**Comment by zhon** [comment]
I too am new to react (just started working on it for code camp) so I would prefer letting Jake recommend the "right" was of doing something.

Some people have store holding business logic other don't.

The schedule page should listen to the store, yes. Usually something calls getData, the store is updated and tells its listeners to update themselves. In the catalog's case we are currently calling an action to getData.

I don't know about stores calling `waitFor` other stores but it is possible. Sometimes you have one store for your entire app other times it is split up. Again I am hoping @jaketrent can help us with these questions.

**Comment by zhon** [comment]
I would like to close this issue and replace it with something like

Story 2 Fix and Refactory Malfoy's code

**Comment by zhon** [comment]
I think Story 2 is finished.
