### ISSUE TITLE
Consider Using sinon.js and jasmine rather than jest

### ISSUE THREAD

**Issue by zhon** [allan-stewart/react-hogwarts-tdd-kata#4]
Jest still has the problem of running with node over versions over 10.

Asking people to downgrade their node just for this session is too much.

**Comment by allan-stewart** [comment]
After Jake added some of the testing depenendencies, I discovered that I could not install `jsdom` because I don't have python 2.7 installed so that `node-gyp` can build `contextify`.

I can probably get around this issue, but I'm worried about taking on any dependencies that require python; especially on Windows. Feels like a setup step that may be hard to deal with for some attendees.

So we might want to switch over to karma instead; that installed for me fine (though I haven't set up any tests for our project with it yet). Thoughts??

**Comment by zhon** [comment]
I am hoping we won't have to test the DOM. We should be able to stick with the virtual DOM.

**Comment by zhon** [comment]
Now Jest is back on the table with the Node 12 fix.

No it is not #8

**Comment by zhon** [comment]
I would like to add karma, and rewire to this list.

Karma to allow debugging in the browser (as well as headless).
Rewire will allow us to mock components.

**Comment by zhon** [comment]
Closing this for #12 and #13
