### ISSUE TITLE
Create React code for Story 1

### ISSUE THREAD

**Issue by zhon** [allan-stewart/react-hogwarts-tdd-kata#5]
Code for rendering catalog is complete. Still need to do the following:
1. Move into `app`
2. Add tests
3. Write up narrative

**Comment by zhon** [comment]
The code has been completed and moved into app. Next we need tests.

**Comment by zhon** [comment]
I have seriously started writing the narrative for story 1.

@allan-stewart, can you give it a run through? The starting code can be found here: https://github.com/zhon/react-hogwarts-tdd-kata-start

**Comment by allan-stewart** [comment]
Sure. I should be able to give it a whirl tonight (as well as do some additional work).

**Comment by zhon** [comment]
I have completed all I want done for Story 1
- Narrative (only language and bug fixes needed)
- code (I have made the course repository return a catalog rather than a promise)
- Tests have been added.

To simplify, I have not done any mocking.

**Comment by allan-stewart** [comment]
@zhon I ran through it tonight and found several small issues which I have fixed in both repos. But there are still a few items I thought I should call out:

When starting from scratch:
- Running `npm start` causes a warning because `course.js` has an unused import of React. (Error says `1:7  error  React is defined but never used  no-unused-vars`). This probably isn't a big deal, but worth noting. Maybe empty the file and add that single line to the readme instead?
- The catalog page seems to be missing the "jumbotron" page header, so it is inconsistent with the other pages.

In section 1.1.2, you have them create the code for the `Course` component... but shouldn't we have them put in a quick test first?

In section 1.1.3 and 1.2.1, the tests pass but there are some React warnings that are written to the console along with the test results. Probably not a big deal, but a bit annoying.

Finally, should there be existing tests for the catalog-page?

**Comment by allan-stewart** [comment]
Also, removing the promise from the catalog repository does seem to have simplified things. I think I may copy that for the wizard repository as well.

**Comment by zhon** [comment]
>  I think I may copy that for the wizard repository as well.

I was hoping to move from simple to more complex. Without the Promise, I was able to avoid `alt` and `flux`altogether. Something registration cannot avoid.

**Comment by zhon** [comment]
> In section 1.1.2, you have them create the code for the Course component... but shouldn't we have them put in a quick test first?

I need to make this clearer. If you get stuck, write or draw the UI. For most frameworks, you just do the html. React JSX is weird in that code looks and acts like `HTML`

**Comment by zhon** [comment]
> In section 1.1.2, you have them create the code for the Course component... but shouldn't we have them put in a quick test first?

I wanted to refactor to the Course component. I normally would add (or move) tests. I just didn't because it is hard to **remove** code in the readme.

**Comment by zhon** [comment]
@allan-stewart, thank you for going through this and providing helpful fixes and comments.
